# Generated by Django 5.2 on 2025-05-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
