# Generated by Django 5.2 on 2025-05-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_remove_profile_avatar_profile_avatar_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_name',
        ),
    ]
